### ISSUE TITLE
Not IPO approved

### ISSUE THREAD

**Issue by TeddyTelanoff** [LapysDev/Experiments#1]
As order of the IPO (Interdimensional Peacemaking Organization), your code may not be ran experimentally without first building on a remote planet. See more at https://ipo-official.github.io/testing.html. And for a license, see [https://ipo-official.github.io/license.html](https://youtu.be/dQw4w9WgXcQ).

**Comment by LapysDev** [comment]
_*acquiring remote planets…_ 🚀
